
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ID = 2;
  public static final int OP_MUL = 7;
  public static final int error = 1;
  public static final int OP_SUMA = 6;
  public static final int CONST_FLOAT = 4;
  public static final int CONST_INT = 3;
  public static final int OP_ASIG = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONST_INT",
  "CONST_FLOAT",
  "OP_ASIG",
  "OP_SUMA",
  "OP_MUL"
  };
}

