
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cte_s = 3;
  public static final int read = 13;
  public static final int id = 2;
  public static final int coma = 12;
  public static final int take = 10;
  public static final int cc = 8;
  public static final int asigna = 15;
  public static final int ca = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int pc = 6;
  public static final int cte = 4;
  public static final int pa = 5;
  public static final int mas = 11;
  public static final int pyc = 9;
  public static final int write = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "cte_s",
  "cte",
  "pa",
  "pc",
  "ca",
  "cc",
  "pyc",
  "take",
  "mas",
  "coma",
  "read",
  "write",
  "asigna"
  };
}

